export const ActionType = {

  //EXAMPLE LIST
  LOAD_LIST: "LOAD_LIST",
  LOAD_LIST_SUCCESSFUL: "LOAD_LIST_SUCCESSFUL",
  LOAD_LIST_FAIL: "LOAD_LIST_FAIL",
  DELETE_LISTITEM: "DELETE_LISTITEM",
  ADD_LISTITEM_SUCCESSFUL: "ADD_LISTITEM_SUCCESSFUL",
  ADD_LISTITEM_FAIL: "ADD_LISTITEM_FAIL",
  DELETE_LISTITEM_SUCCESSFUL: "DELETE_LISTITEM_SUCCESSFUL",
  DELETE_LISTITEM_FAIL: "DELETE_LISTITEM_FAIL",

  //TAGS LIST
  FETCH_TAG_LIST_DATA: "FETCH_TAG_LIST_DATA",
  FETCH_TAG_CATEGORIES_DATA: "FETCH_TAG_CATEGORIES_DATA",
  CREATE_TAG: "CREATE_TAG",
  DELETE_TAG: "DELETE_TAG",  
  EDIT_TAG: "EDIT_TAG",
  CHECK_TAG: "CHECK_TAG",

  // ANY COMPONENT
  LOAD_COMPONENT: "LOAD_COMPONENT",
  LOAD_COMPONENT_FAIL: "LOAD_COMPONENT_FAIL",
  ADD_COMPONENT_FAIL: "ADD_COMPONENT_FAIL",
  EDIT_COMPONENT_FAIL: "EDIT_COMPONENT_FAIL",
  DELETE_COMPONENT_FAIL: "DELETE_COMPONENT_FAIL",

  // SCHEDULER
  SCHEDULER_LOAD_RESOURCES: "SCHEDULER_LOAD_RESOURCES",
  SCHEDULER_LOAD_EVENTS: "SCHEDULER_LOAD_EVENTS",
  SCHEDULER_ADD_NEW_EVENT: "SCHEDULER_ADD_NEW_EVENT",
  SCHEDULER_EDIT_EVENT: "SCHEDULER_EDIT_EVENT",
  SCHEDULER_DELETE_EVENT: "SCHEDULER_DELETE_EVENT",

  // CATEGORY LIST
  LOAD_CATEGORY_LIST: "LOAD_CATEGORY_LIST",
  LOAD_SUBCATEGORY_LIST: "LOAD_SUBCATEGORY_LIST",

  ADD_CATEGORY: "ADD_CATEGORY",
  ADD_SUBCATEGORY: "ADD SUBCATEGORY",

  EDIT_CATEGORY: "EDIT_CATEGORY",
  EDIT_SUBCATEGORY: "EDIT_SUBCATEGORY",

  DELETE_CATEGORY: "DELETE_CATEGORY",
  DELETE_SUBCATEGORY: "DELETE_SUBCATEGORY",
};
